### ISSUE TITLE
Hitting error when upgrading to gradle 3.4-rc-1

### ISSUE THREAD

**Issue by gpmo** [palantir/gradle-configuration-resolver-plugin#25]
Hey @nmiyake and @atrocities,

I'm running into the following error when trying to upgradle to latest:

```
Caused by: java.lang.IllegalStateException: Resolving configuration 'apiElements' directly is not allowed
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.assertResolvingAllowed(DefaultConfiguration.java:818)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveToStateOrLater(DefaultConfiguration.java:419)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.doGetFiles(DefaultConfiguration.java:515)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.getFiles(DefaultConfiguration.java:367)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration_Decorated.getFiles(Unknown Source)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolve(DefaultConfiguration.java:363)
        at org.gradle.api.artifacts.Configuration$resolve$9.call(Unknown Source)
        at com.palantir.configurationresolver.ResolveConfigurationsTask$_resolveAllConfigurations_closure1.doCall(ResolveConfigurationsTask.groovy:25)
        at sun.reflect.GeneratedMethodAccessor895.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024)
        at groovy.lang.Closure.call(Closure.java:414)
        at groovy.lang.Closure.call(Closure.java:430)
        at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:70)
        at org.gradle.util.ConfigureUtil.configureTarget(ConfigureUtil.java:160)
        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:106)
        at org.gradle.util.ConfigureUtil$1.execute(ConfigureUtil.java:123)
        at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:135)
        at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:153)
        at org.gradle.api.DomainObjectCollection$all$1.call(Unknown Source)
        at com.palantir.configurationresolver.ResolveConfigurationsTask.resolveAllConfigurations(ResolveConfigurationsTask.groovy:24)
        at sun.reflect.GeneratedMethodAccessor899.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:141)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:123)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:632)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:615)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:95)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:76)
        ... 23 more
```

Reason for my upgrade is so that I can use the default jacoco coverage that comes with the latest gradle version.

**Comment by gpmo** [comment]
Hey @nmiyake, do you have any updates?

**Comment by nmiyake** [comment]
Hey sorry, this is not one of my primary projects and have been busy with other things that are more pressing. I'm also going to be out for about 2 weeks pretty soon, so to be perfectly honest it's possible that I won't be able to really engage on this for a while.

I would follow up with @atrocities or one of our internal teams that make use of this plugin to see if they can provide any help.

**Comment by atrocities** [comment]
It's because Gradle 3.3+ has introduced configurations that are not resolvable. See https://github.com/gradle/gradle/pull/1351

https://github.com/palantir/gradle-configuration-resolver-plugin/pull/26

**Comment by atrocities** [comment]
Fixed - https://plugins.gradle.org/plugin/com.palantir.configuration-resolver/0.2.0
